// Part of the Knowledge Commons Repository
// Copyright (C) 2023-2026 MESH Research
//
// based on portions of InvenioRDM
// Copyright (C) 2020-2022 CERN.
// Copyright (C) 2020-2022 Northwestern University.
// Copyright (C) 2021-2022 Graz University of Technology.
// Copyright (C) 2022-2023 KTH Royal Institute of Technology.
//
// The Knowledge Commons Repository and Invenio App RDM are both free software;
// you can redistribute them and/or modify them
// under the terms of the MIT License; see LICENSE file for more details.

import React, { useMemo } from "react";
import { DepositFormApp } from "@js/invenio_rdm_records";
import PropTypes from "prop-types";
import { i18next } from "@translations/invenio_modular_deposit_form/i18next";
import { componentsRegistry } from "./componentsRegistry";
import { buildFormSections } from "./buildFormStructure";
import { FormLayoutContainer } from "./FormLayoutContainer";
import { FormUIStateManager } from "./FromUIStateManager";

// Validator module: resolved via webpack alias @js/invenio_modular_deposit_form_validator
// (package default or entry-point override). Contract: module exports a single value
// (default or module.exports). If callable, it is the schema builder (config) => schema;
// otherwise it is the schema itself. Schema only — no separate validate function.
const validatorModule = require(`@js/invenio_modular_deposit_form_validator`);
const validatorExport = validatorModule?.default ?? validatorModule;

/*
RDMDepositForm is the main component that we override to customize the deposit form. Vocabulary handling matches stock invenio-app-rdm: we read config.vocabularies and build an enriched vocabularies object (creator/contributor type options). Config (including enriched vocabularies and componentsRegistry) is passed to DepositFormApp and stored in Redux; FormLayoutContainer reads them from the store.
*/
export const RDMDepositForm = ({
  config,
  files,
  filesLocked,
  permissions,
  preselectedCommunity,
  record,
  useUppy,
  recordRestrictionGracePeriod,
  allowRecordRestriction,
  groupsEnabled,
  allowEmptyFiles,
  recordDeletion,
  fileModification,
  shareBtnRequireLinkExpiration,
}) => {
  // Apply PID config overrides before config is stored (DepositFormApp puts config in Redux)
  const pidsConfigOverrides = config.pids_config_overrides ?? {};
  if (!!pidsConfigOverrides?.doi && Array.isArray(config.pids)) {
    const doiPid = config.pids.find((pid) => pid.scheme === "doi");
    if (doiPid) {
      Object.assign(doiPid, pidsConfigOverrides.doi);
    }
  }

  // TODO: Make ALL vocabulary be generated by backend.
  // Currently, some vocabulary is generated by backend and some is
  // generated by frontend here. Same as stock invenio-app-rdm RDMDepositForm.
  const creatorRoleVocab = config.vocabularies.creators?.role;
  const contributorRoleVocab = config.vocabularies.contributors?.role;
  const roleVocabForCreators =
    Array.isArray(creatorRoleVocab) && creatorRoleVocab.length > 0
      ? creatorRoleVocab
      : contributorRoleVocab;

  const vocabularies = config.vocabularies
    ? {
        metadata: {
          ...config.vocabularies,

          creators: {
            ...config.vocabularies.creators,
            // Backend forms_config often only sends `contributors.role`; stock UIs use the
            // same creatibutor role vocab for both — fall back when creators.role is missing
            // or empty (not just nullish — `[]` would otherwise block `??` fallback).
            role: roleVocabForCreators,
            type: [
              { text: i18next.t("Person"), value: "personal" },
              { text: i18next.t("Organization"), value: "organizational" },
            ],
          },

          contributors: {
            ...config.vocabularies.contributors,
            type: [
              { text: i18next.t("Person"), value: "personal" },
              { text: i18next.t("Organization"), value: "organizational" },
            ],
          },
          identifiers: {
            ...config.vocabularies.identifiers,
          },
        },
      }
    : { metadata: {} };

  const formSectionFields = buildFormSections(
    config.common_fields,
    config.fields_by_type,
    componentsRegistry
  );

  const configForStore = {
    ...config,
    files_locked: filesLocked ?? false,
    use_uppy: useUppy ?? false,
    record_restriction_grace_period:
      recordRestrictionGracePeriod != null ? Number(recordRestrictionGracePeriod) : 30,
    allow_record_restriction: allowRecordRestriction ?? true,
    groups_enabled: groupsEnabled ?? undefined,
    allow_empty_files: allowEmptyFiles ?? true,
    vocabularies,
    componentsRegistry,
    formSectionFields,
  };

  // V14-only: add to config only when present (v13 view/config may not provide them)
  if (recordDeletion != null) {
    configForStore.record_deletion = recordDeletion;
  }
  if (fileModification != null) {
    configForStore.file_modification = fileModification;
  }
  if (shareBtnRequireLinkExpiration != null) {
    configForStore.require_secret_links_expiration = shareBtnRequireLinkExpiration;
  }

  const validationSchema = useMemo(() => {
    if (typeof validatorExport === "function") return validatorExport(configForStore);
    return validatorExport ?? null;
  }, [config]);

  return (
    <DepositFormApp
      config={configForStore}
      record={record}
      preselectedCommunity={preselectedCommunity}
      files={files}
      permissions={permissions}
      errors={record.errors}
      validationSchema={validationSchema}
    >
      <FormUIStateManager>
        <FormLayoutContainer />
      </FormUIStateManager>
    </DepositFormApp>
  );
};

RDMDepositForm.propTypes = {
  config: PropTypes.object.isRequired,
  record: PropTypes.object.isRequired,
  files: PropTypes.object,
  filesLocked: PropTypes.bool,
  permissions: PropTypes.object,
  preselectedCommunity: PropTypes.object,
  useUppy: PropTypes.bool,
  recordRestrictionGracePeriod: PropTypes.oneOfType([PropTypes.number, PropTypes.string]),
  allowRecordRestriction: PropTypes.bool,
  groupsEnabled: PropTypes.bool,
  allowEmptyFiles: PropTypes.bool,
  recordDeletion: PropTypes.object,
  fileModification: PropTypes.object,
  shareBtnRequireLinkExpiration: PropTypes.bool,
};

RDMDepositForm.defaultProps = {
  files: null,
  filesLocked: false,
  permissions: null,
  preselectedCommunity: undefined,
  useUppy: false,
  recordRestrictionGracePeriod: undefined,
  allowRecordRestriction: undefined,
  groupsEnabled: undefined,
  allowEmptyFiles: undefined,
  recordDeletion: undefined,
  fileModification: undefined,
  shareBtnRequireLinkExpiration: undefined,
};
